### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm

### ISSUE THREAD

**Issue by nubonics** [dark-0ne/ForexTrader#1]
Im trying to run the block
`num_episodes = 1
episode_durations = []

for i_episode in range(num_episodes):
    # Initialize the environment and state
    env.reset()
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)
    state = torch.tensor(state.drop('Timestamp',axis=1).values).view(1,-1)
    for t in count():
        # Select and perform an action
        action = select_action(state)
        next_state, reward, done, info = env.step(action.item())
        next_state = torch.tensor(next_state.drop('Timestamp',axis=1).values).view(1,-1)
        reward = torch.tensor([reward],device=device)

        
        # Store the transition in memory
        memory.push(state, action, next_state, reward)

        # Move to the next state
        state = next_state

        # Perform one step of the optimization (on the target network)
        optimize_model()
        if done:
            episode_durations.append(t + 1)
            break
    # Update the target network, copying all weights and biases in DQN
    print("Episode {} done.".format(i_episode))
    if i_episode % TARGET_UPDATE == 0:
        target_net.load_state_dict(policy_net.state_dict())

print('Complete')`

However, I am encountering the traceback as follows:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-35ad5f66f49b> in <module>
     23 
     24         # Perform one step of the optimization (on the target network)
---> 25         optimize_model()
     26         if done:
     27             episode_durations.append(t + 1)

<ipython-input-25-f83ecdf511ae> in optimize_model()
     22     # columns of actions taken. These are the actions which would've been taken
     23     # for each batch state according to policy_net
---> 24     state_action_values = policy_net(state_batch).gather(1, action_batch)
     25 
     26     # Compute V(s_{t+1}) for all next states.

c:\users\nubonix\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

<ipython-input-15-081efa1d3af5> in forward(self, x)
      8 
      9     def forward(self, x):
---> 10         x = F.relu(self.lin1(x.float()))
     11         x = F.relu(self.lin2(x.float()))
     12         x = F.softmax(self.lin3(x.float()))

c:\users\nubonix\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

c:\users\nubonix\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     85 
     86     def forward(self, input):
---> 87         return F.linear(input, self.weight, self.bias)
     88 
     89     def extra_repr(self):

c:\users\nubonix\appdata\local\programs\python\python37\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1368     if input.dim() == 2 and bias is not None:
   1369         # fused op is marginally faster
-> 1370         ret = torch.addmm(bias, input, weight.t())
   1371     else:
   1372         output = input.matmul(weight.t())

RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm
```

**Comment by dark-0ne** [comment]
I'm afraid I have no idea what the problem might be. I have tried the notebook both on cpu(on my local machine) and gpu(Colab) and it worked fine in both cases so I don't think there is something wrong with the code. I can only suggest you make sure your pytorch packages are installed and working correctly
